title: Mandarin Reclist
description: A possible minimal Mandarin singing voicebank reclist.
remote_theme: just-the-docs/just-the-docs

url: https://just-the-docs.github.io

aux_links:
  Back to my works: https://slidingwall.github.io/works/
